"use client";
import { useEffect, useMemo, useState } from "react";
import { collection, doc, onSnapshot, query, runTransaction, serverTimestamp } from "firebase/firestore";
import { getDownloadURL, ref } from "firebase/storage";
import { Check, Download, Eye, FileDown, Search, X } from "lucide-react";
import { auth, db, storage } from "../lib/firebase";
import { PROGRAM_ID, maskIdentification } from "../lib/registration";
import { rm } from "../lib/finance";
import { requestRegistrationEmail } from "../lib/registration-email";
import { downloadConfirmationLetterPdf } from "../lib/registration-documents";

type Registration={id:string;referenceNumber:string;fullName:string;identificationNumber:string;email:string;organisationType:string;workplace:string;expertise:string;attendanceType:string;attendanceLabel:string;registrationFeeInSen:number;paymentStatus:string;registrationStatus:string;submittedAt?:{toDate:()=>Date};proofOfPaymentPath:string;linkedTransactionId?:string};

export default function AdminRegistrations({notify}:{notify:(s:string)=>void}) {
  const [rows,setRows]=useState<Registration[]>([]),[search,setSearch]=useState(""),[payment,setPayment]=useState("all"),[status,setStatus]=useState("all"),[selected,setSelected]=useState<Registration|null>(null),[error,setError]=useState("");
  useEffect(()=>{if(!db)return;return onSnapshot(query(collection(db,"programs",PROGRAM_ID,"registrations")),snap=>setRows(snap.docs.map(x=>x.data() as Registration)),()=>setError("Registrations could not be loaded. Retry after checking your connection."))},[]);
  const filtered=useMemo(()=>rows.filter(r=>(payment==="all"||r.paymentStatus===payment)&&(status==="all"||r.registrationStatus===status)&&`${r.fullName} ${r.email} ${r.referenceNumber}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b.submittedAt?.toDate().getTime()||0)-(a.submittedAt?.toDate().getTime()||0)),[rows,search,payment,status]);
  const verified=rows.filter(r=>r.paymentStatus==="verified"),expected=rows.filter(r=>r.registrationStatus!=="cancelled"&&r.registrationStatus!=="rejected").reduce((s,r)=>s+r.registrationFeeInSen,0);

  const verify=async(r:Registration)=>{
    if(!db||!auth?.currentUser||!confirm(`Verify payment for ${r.referenceNumber} and create its income transaction?`))return;
    try {
      const regRef=doc(db,"programs",PROGRAM_ID,"registrations",r.id);
      await runTransaction(db,async tx=>{
        const current=(await tx.get(regRef)).data() as Registration;
        if(current.paymentStatus==="verified"||current.linkedTransactionId)return;
        const transactionId=crypto.randomUUID();
        tx.set(doc(db,"programs",PROGRAM_ID,"transactions",transactionId),{id:transactionId,programId:PROGRAM_ID,type:"income",amountInSen:current.registrationFeeInSen,category:"Participant Fees",description:`Registration payment - ${current.fullName}`,partyName:current.fullName,paymentMethod:"Bank Transfer",referenceNumber:current.referenceNumber,transactionDate:new Date().toISOString().slice(0,10),status:"paid",createdBy:auth.currentUser!.uid,createdAt:serverTimestamp(),updatedBy:auth.currentUser!.uid,updatedAt:serverTimestamp(),source:"registration",registrationId:r.id});
        tx.update(regRef,{paymentStatus:"verified",registrationStatus:"confirmed",verifiedAt:serverTimestamp(),verifiedBy:auth.currentUser!.uid,linkedTransactionId:transactionId,updatedAt:serverTimestamp()});
      });
      const emailSent=await requestRegistrationEmail(auth.currentUser,r.id,"confirmed");
      notify(emailSent?"Payment verified, income created and confirmation email requested":"Payment verified and income created. Email service is not configured or temporarily unavailable.");
    } catch { setError("Payment verification failed. No financial changes were saved."); }
  };
  const reject=async(r:Registration)=>{if(!db||!auth?.currentUser)return;const reason=prompt("Reason for rejecting this payment proof:");if(!reason)return;await runTransaction(db,async tx=>tx.update(doc(db,"programs",PROGRAM_ID,"registrations",r.id),{paymentStatus:"rejected",registrationStatus:"rejected",rejectionReason:reason,updatedAt:serverTimestamp(),updatedBy:auth.currentUser!.uid}));notify("Registration rejected")};
  const viewProof=async(r:Registration)=>{if(!storage||!r.proofOfPaymentPath)return;try{window.open(await getDownloadURL(ref(storage,r.proofOfPaymentPath)),"_blank","noopener,noreferrer")}catch{setError("The payment proof could not be opened.")}};
  const confirmationLetter=(r:Registration)=>downloadConfirmationLetterPdf({referenceNumber:r.referenceNumber,fullName:r.fullName,attendanceLabel:r.attendanceLabel,feeInSen:r.registrationFeeInSen,date:r.submittedAt?.toDate()||new Date()});
  const csv=()=>{const lines=[["Reference Number","Participant Name","Email","Identification (Masked)","Organisation","Workplace","Expertise","Attendance","Fee (RM)","Payment Status","Registration Status","Submission Date"],...filtered.map(r=>[r.referenceNumber,r.fullName,r.email,maskIdentification(r.identificationNumber),r.organisationType,r.workplace,r.expertise,r.attendanceLabel,(r.registrationFeeInSen/100).toFixed(2),r.paymentStatus,r.registrationStatus,r.submittedAt?.toDate().toISOString()||""])].map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",lines],{type:"text/csv;charset=utf-8"}));a.download="filtered-registrations.csv";a.click();URL.revokeObjectURL(a.href)};

  return <>
    <div className="page-heading"><div><span className="eyebrow">PARTICIPANT ADMINISTRATION</span><h1>Registrations</h1><p>Review submissions, verify payments and confirm participant places.</p></div><button className="premium-btn primary" onClick={csv}><Download/>Export CSV</button></div>
    <section className="budget-overview phase4-summary">{[["TOTAL REGISTRATIONS",rows.length],["PENDING VERIFICATION",rows.filter(r=>r.paymentStatus==="pending_verification").length],["CONFIRMED",rows.filter(r=>r.registrationStatus==="confirmed").length],["REJECTED",rows.filter(r=>r.registrationStatus==="rejected").length],["DAY 1 ONLY",rows.filter(r=>r.attendanceType==="day1").length],["FULL PROGRAMME",rows.filter(r=>r.attendanceType==="full").length],["EXPECTED INCOME",rm(expected)],["VERIFIED INCOME",rm(verified.reduce((s,r)=>s+r.registrationFeeInSen,0))]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</section>
    {error&&<div className="budget-warning"><span>{error}</span><button onClick={()=>setError("")}><X/></button></div>}
    <div className="filter-bar"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or reference"/></div><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">All payment statuses</option><option value="pending_verification">Pending verification</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All registration statuses</option><option value="submitted">Submitted</option><option value="confirmed">Confirmed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select></div>
    <article className="finance-panel table-panel"><div className="table-meta"><b>{filtered.length} registrations</b><span>Identification numbers are masked by default</span></div><div className="transaction-table"><table><thead><tr><th>Reference</th><th>Participant</th><th>Organisation</th><th>Attendance</th><th>Fee</th><th>Payment</th><th>Registration</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.referenceNumber}</b><small>{maskIdentification(r.identificationNumber)}</small></td><td><b>{r.fullName}</b><small>{r.email}</small></td><td><b>{r.organisationType}</b><small>{r.workplace}</small></td><td>{r.attendanceType==="full"?"Day 1 + 2":"Day 1"}</td><td>{rm(r.registrationFeeInSen)}</td><td><span className={`status ${r.paymentStatus}`}>{r.paymentStatus.replaceAll("_"," ")}</span></td><td><span className={`status ${r.registrationStatus}`}>{r.registrationStatus}</span></td><td>{r.submittedAt?.toDate().toLocaleDateString("en-MY")||"—"}</td><td><button className="row-menu" aria-label="View registration" onClick={()=>setSelected(r)}><Eye/></button><button className="row-menu" aria-label="View proof" onClick={()=>viewProof(r)}><Download/></button>{r.paymentStatus==="pending_verification"&&<><button className="row-menu" aria-label="Verify payment" onClick={()=>verify(r)}><Check/></button><button className="row-menu danger" aria-label="Reject payment" onClick={()=>reject(r)}><X/></button></>}{r.paymentStatus==="verified"&&<button className="row-menu" aria-label="Download confirmation letter" onClick={()=>confirmationLetter(r)}><FileDown/></button>}</td></tr>)}</tbody></table></div></article>
    {selected&&<><div className="modal-backdrop" onClick={()=>setSelected(null)}/><div className="confirm-dialog registration-detail"><button className="row-menu" onClick={()=>setSelected(null)}><X/></button><h3>{selected.referenceNumber}</h3><p><b>{selected.fullName}</b><br/>{selected.email}</p><dl><div><dt>Identification</dt><dd>{selected.identificationNumber}</dd></div><div><dt>Workplace</dt><dd>{selected.workplace}</dd></div><div><dt>Expertise</dt><dd>{selected.expertise}</dd></div><div><dt>Attendance</dt><dd>{selected.attendanceLabel}</dd></div></dl>{selected.paymentStatus==="verified"&&<button className="premium-btn primary" onClick={()=>confirmationLetter(selected)}><FileDown/>Download Confirmation Letter</button>}</div></>}
  </>;
}
