"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { doc, onSnapshot } from "firebase/firestore";
import { ArrowRight, Bone, Brain, HeartPulse, Sparkles, Stethoscope, Users } from "lucide-react";
import { motion } from "framer-motion";
import PublicLayout from "./PublicLayout";
import { db } from "./lib/firebase";
import { PROGRAM_ID } from "./lib/registration";

const disciplines=[
  [HeartPulse,"Neonatology and Paediatrics"],[Bone,"Oral and Maxillofacial Surgery"],[Stethoscope,"Otorhinolaryngology"],[Sparkles,"Paediatric Dentistry"],[Users,"Other related healthcare disciplines"],
] as const;
type PublicEventSettings={introduction?:string;eventDate?:string;venue?:string;registrationClosingDate?:string};
export default function EventHomepage(){const [settings,setSettings]=useState<PublicEventSettings>({});useEffect(()=>{if(!db)return;return onSnapshot(doc(db,"programs",PROGRAM_ID,"public","event"),snap=>setSettings(snap.data()||{}))},[]);return <PublicLayout><main>
  <section className="public-hero"><div className="hero-pattern"/><motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.55}}><span className="gold-kicker">SYMPOSIUM &amp; WORKSHOP</span><h1>Symposium on Management of <em>Pierre Robin Sequence</em> in Infants 2026</h1><p>From Airway to Oral Rehabilitation: A Collaborative Approach</p>{(settings.eventDate||settings.venue||settings.registrationClosingDate)&&<div className="hero-event-meta">{settings.eventDate&&<span>{new Date(`${settings.eventDate}T00:00:00`).toLocaleDateString("en-MY",{dateStyle:"long"})}</span>}{settings.venue&&<span>{settings.venue}</span>}{settings.registrationClosingDate&&<span>Register by {new Date(`${settings.registrationClosingDate}T00:00:00`).toLocaleDateString("en-MY",{dateStyle:"long"})}</span>}</div>}<div className="hero-actions"><Link className="gold-button" href="/register">Register Now <ArrowRight/></Link><a className="outline-button" href="#programme">View Programme</a></div></motion.div><motion.div className="medical-orbit" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.7}} aria-hidden="true"><span/><span/><span/><div><Brain/><b>Multidisciplinary<br/>Infant Care</b></div></motion.div></section>
  <section className="public-section about" id="about"><div><span className="gold-kicker">ABOUT THE EVENT</span><h2>One patient journey.<br/><em>Many clinical perspectives.</em></h2></div><p>{settings.introduction||"This symposium brings together healthcare professionals involved in the multidisciplinary care of infants with Pierre Robin Sequence. The programme explores the patient journey from early airway management to feeding support and oral rehabilitation through collaborative clinical practice."}</p></section>
  <section className="public-section disciplines"><div className="section-heading"><span className="gold-kicker">COLLABORATIVE APPROACH</span><h2>Disciplines connected by better outcomes</h2></div><div className="discipline-grid">{disciplines.map(([Icon,label],i)=><motion.article key={label} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} whileHover={{y:-4}}><Icon/><b>{label}</b></motion.article>)}</div></section>
  <section className="public-section programme" id="programme"><div className="section-heading"><span className="gold-kicker">PROGRAMME OVERVIEW</span><h2>Two focused days of shared practice</h2><p>Detailed schedules and speaker information will be published when confirmed.</p></div><div className="day-grid"><article><span>DAY 01</span><h3>Symposium</h3><p>Multidisciplinary perspectives across airway, feeding and oral rehabilitation.</p></article><article className="featured"><span>DAY 02</span><h3>Workshop on Fabrication of OAP</h3><p>A focused practical workshop complementing the symposium programme.</p></article></div></section>
  <section className="public-section attendance" id="attendance"><div className="section-heading"><span className="gold-kicker">ATTENDANCE OPTIONS</span><h2>Choose your learning experience</h2></div><div className="price-grid"><article><span>DAY 1 ONLY</span><h3>Symposium</h3><strong>RM150</strong><small>Limited to 140 participants</small><Link className="outline-button" href="/register?attendance=day1">Select and Register</Link></article><article className="recommended"><i>FULL PROGRAMME</i><span>DAY 1 &amp; DAY 2</span><h3>Symposium and Workshop on Fabrication of OAP</h3><strong>RM300</strong><small>Limited to 15 participants</small><Link className="gold-button" href="/register?attendance=full">Select and Register</Link></article></div></section>
  <section className="public-section audience"><div className="section-heading"><span className="gold-kicker">WHO SHOULD ATTEND</span><h2>Designed for the multidisciplinary care team</h2></div><ul>{["Neonatologists","Paediatricians","Oral and Maxillofacial Surgeons","Otorhinolaryngologists","Paediatric Dentists","Other related healthcare professionals"].map(x=><li key={x}>{x}</li>)}</ul></section>
  <section className="public-cta"><span className="gold-kicker">REGISTRATION IS OPEN</span><h2>Join the conversation shaping collaborative PRS care.</h2><p>Submit your registration and proof of payment for organiser verification.</p><Link className="gold-button" href="/register">Register Now <ArrowRight/></Link></section>
  </main></PublicLayout>}
