"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Check, ChevronLeft, ChevronRight, Copy, FileCheck, Upload, X } from "lucide-react";
import { doc, onSnapshot } from "firebase/firestore";
import PublicLayout from "../PublicLayout";
import { db } from "../lib/firebase";
import { ATTENDANCE, emptyRegistration, maskIdentification, PROGRAM_ID, submitRegistration, validateProof, type RegistrationDraft } from "../lib/registration";

const orgs=["Private","Government","Academic Institution","Other"], expertise=["Neonatologist / Paediatrician","Oral and Maxillofacial Surgeon","Otorhinolaryngology","Paediatric Dentistry","Other"], foods=["Normal Diet","Vegetarian","Other"];
export default function RegisterPage(){
 const query=useSearchParams(),router=useRouter(); const selected=query.get("attendance")==="full"?"full":"day1";
 const [step,setStep]=useState(1),[form,setForm]=useState<RegistrationDraft>({...emptyRegistration,attendanceType:selected}),[errors,setErrors]=useState<Record<string,string>>({}),[submitting,setSubmitting]=useState(false),[progress,setProgress]=useState(0),[copied,setCopied]=useState(false),[showTerms,setShowTerms]=useState(false),[eventSettings,setEventSettings]=useState<{registrationEnabled?:boolean;registrationOpeningDate?:string;registrationClosingDate?:string}>({});
 useEffect(()=>{if(!db)return;return onSnapshot(doc(db,"programs",PROGRAM_ID,"public","event"),snap=>setEventSettings(snap.data()||{}))},[]);
 useEffect(()=>{if(!showTerms)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setShowTerms(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[showTerms]);
 const today=new Date().toISOString().slice(0,10);const closed=eventSettings.registrationEnabled===false||(eventSettings.registrationOpeningDate&&today<eventSettings.registrationOpeningDate)||(eventSettings.registrationClosingDate&&today>eventSettings.registrationClosingDate);
 const fee=ATTENDANCE[form.attendanceType]; const update=(key:keyof RegistrationDraft,value:string|boolean|File|null)=>setForm(v=>({...v,[key]:value}));
 const validate=(target=step)=>{const e:Record<string,string>={};if(target===1){if(!form.fullName.trim())e.fullName="Full name is required.";if(!form.identificationNumber.trim())e.identificationNumber="IC or passport number is required.";if(!/^\S+@\S+\.\S+$/.test(form.email))e.email="Enter a valid email address.";if(!/^[+\d][\d\s()-]{7,}$/.test(form.phoneNumber))e.phoneNumber="Enter a valid phone number."}if(target===2){if(!form.organisationType)e.organisationType="Select an organisation type.";if(form.organisationType==="Other"&&!form.organisationTypeOther.trim())e.organisationTypeOther="Please specify the organisation type.";if(!form.workplace.trim())e.workplace="Workplace is required.";if(!form.expertise)e.expertise="Select an area of expertise.";if(form.expertise==="Other"&&!form.expertiseOther.trim())e.expertiseOther="Please specify the area of expertise.";if(!form.foodPreference)e.foodPreference="Select a food preference.";if(form.foodPreference==="Other"&&!form.foodPreferenceOther.trim())e.foodPreferenceOther="Please specify the food preference."}if(target===3){const proof=validateProof(form.proofFile);if(proof)e.proofFile=proof}if(target===4){if(!form.informationConfirmation)e.informationConfirmation="Confirmation is required.";if(!form.privacyConsent)e.privacyConsent="Consent is required.";if(!form.termsAccepted)e.termsAccepted="Acceptance is required."}setErrors(e);return !Object.keys(e).length};
 const next=()=>{if(validate())setStep(s=>Math.min(4,s+1))}; const submit=async()=>{if(!form.termsAccepted){setErrors(current=>({...current,termsAccepted:"Please review and accept the Registration Terms before submitting."}));setShowTerms(true);return}if(!validate(1)||!validate(2)||!validate(3)||!validate(4))return;setSubmitting(true);try{const result=await submitRegistration(form,setProgress);sessionStorage.setItem(`registration:${result.referenceNumber}`,JSON.stringify(result));router.push(`/registration-success/${result.referenceNumber}`)}catch(error){const message=error instanceof Error&&error.message.includes("participant limit")?error.message:"Registration could not be submitted. Please check your connection and try again.";setErrors({submit:message});setSubmitting(false)}};
 if(closed)return <PublicLayout><main className="success-page"><section><span className="gold-kicker">REGISTRATION</span><h1>Registration Closed</h1><p>Registration is not currently accepting submissions. It may be closed by the organiser or by the configured registration period.</p><Link className="gold-button" href="/">Return to Homepage</Link></section></main></PublicLayout>; return <PublicLayout><main className="registration-page"><header><span className="gold-kicker">PARTICIPANT REGISTRATION</span><h1>Register for PRS Symposium 2026</h1><p>Your registration remains pending until the organiser verifies your proof of payment.</p></header><div className="stepper" aria-label={`Step ${step} of 4`}>{["Personal","Professional","Attendance & Payment","Review"].map((x,i)=><div className={step>=i+1?"active":""} key={x}><span>{step>i+1?<Check/>:i+1}</span><b>{x}</b></div>)}</div><section className="registration-card" aria-live="polite">
 {step===1&&<><FormHead number="01" title="Personal Information"/><div className="registration-grid"><Field label="Full Name" error={errors.fullName}><input value={form.fullName} onChange={e=>update("fullName",e.target.value)} autoComplete="name"/></Field><Field label="Identification Number" error={errors.identificationNumber}><input value={form.identificationNumber} onChange={e=>update("identificationNumber",e.target.value)} autoComplete="off"/></Field><Field label="Email Address" error={errors.email}><input type="email" value={form.email} onChange={e=>update("email",e.target.value)} autoComplete="email"/></Field><Field label="Phone Number" error={errors.phoneNumber}><input value={form.phoneNumber} onChange={e=>update("phoneNumber",e.target.value)} autoComplete="tel"/></Field></div></>}
 {step===2&&<><FormHead number="02" title="Professional Information"/><div className="registration-grid"><SelectField label="Organisation Type" value={form.organisationType} values={orgs} onChange={v=>update("organisationType",v)} error={errors.organisationType}/>{form.organisationType==="Other"&&<Field label="Other Organisation Type" error={errors.organisationTypeOther}><input value={form.organisationTypeOther} onChange={e=>update("organisationTypeOther",e.target.value)}/></Field>}<Field label="Workplace" error={errors.workplace}><input value={form.workplace} onChange={e=>update("workplace",e.target.value)}/></Field><SelectField label="Area of Expertise" value={form.expertise} values={expertise} onChange={v=>update("expertise",v)} error={errors.expertise}/>{form.expertise==="Other"&&<Field label="Other Area of Expertise" error={errors.expertiseOther}><input value={form.expertiseOther} onChange={e=>update("expertiseOther",e.target.value)}/></Field>}<SelectField label="Food Preference" value={form.foodPreference} values={foods} onChange={v=>update("foodPreference",v)} error={errors.foodPreference}/>{form.foodPreference==="Other"&&<Field label="Other Food Preference" error={errors.foodPreferenceOther}><input value={form.foodPreferenceOther} onChange={e=>update("foodPreferenceOther",e.target.value)}/></Field>}</div></>}
 {step===3&&<><FormHead number="03" title="Attendance and Payment"/><div className="attendance-picker">{Object.entries(ATTENDANCE).map(([key,x])=><button className={form.attendanceType===key?"active":""} onClick={()=>update("attendanceType",key)} key={key}><span>{x.label}</span><b>RM{(x.feeInSen/100).toFixed(0)}</b></button>)}</div><div className="payment-card"><span>BANK TRANSFER DETAILS</span><dl><div><dt>Account Name</dt><dd>Kelab Latihan, Penyelidikan Dan Kecemerlangan Insan Hospital Sultan Ismail</dd></div><div><dt>Account Number</dt><dd><b>36500007868</b><button onClick={async()=>{await navigator.clipboard.writeText("36500007868");setCopied(true)}}><Copy/>{copied?"Copied":"Copy"}</button></dd></div><div><dt>Bank</dt><dd>Hong Leong Bank</dd></div></dl></div><Field label="Proof of Payment" error={errors.proofFile}><label className="payment-upload"><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>update("proofFile",e.target.files?.[0]||null)}/>{form.proofFile?<><FileCheck/><span><b>{form.proofFile.name}</b><small>Click to replace</small></span></>:<><Upload/><span><b>Upload payment proof</b><small>PDF, JPG or PNG · Maximum 10 MB</small></span></>}</label></Field></>}
 {step===4&&<><FormHead number="04" title="Review and Submit"/><div className="review-list">{[["Full Name",form.fullName.toUpperCase()],["Identification Number",maskIdentification(form.identificationNumber)],["Email",form.email],["Phone",form.phoneNumber],["Organisation",form.organisationType==="Other"?form.organisationTypeOther:form.organisationType],["Workplace",form.workplace],["Expertise",form.expertise==="Other"?form.expertiseOther:form.expertise],["Food Preference",form.foodPreference==="Other"?form.foodPreferenceOther:form.foodPreference],["Attendance",fee.label],["Registration Fee",`RM${(fee.feeInSen/100).toFixed(2)}`],["Payment Proof",form.proofFile?.name||""]].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="consents"><CheckField checked={form.informationConfirmation} onChange={v=>update("informationConfirmation",v)} error={errors.informationConfirmation}>I confirm that the information provided is accurate.</CheckField><CheckField checked={form.privacyConsent} onChange={v=>update("privacyConsent",v)} error={errors.privacyConsent}>I consent to the collection and processing of my personal information for event registration and administration purposes. <Link href="/privacy">Privacy Notice</Link></CheckField><div className="terms-consent"><button type="button" className={form.termsAccepted?"terms-review accepted":"terms-review"} onClick={()=>setShowTerms(true)}><span aria-hidden="true">{form.termsAccepted?<Check/>:"!"}</span><div><b>{form.termsAccepted?"Registration Terms accepted":"Review Registration Terms"}</b><small>Open and read the terms before confirming your registration.</small></div></button>{errors.termsAccepted&&<small className="form-error" role="alert">{errors.termsAccepted}</small>}</div></div>{errors.submit&&<p className="form-error submit-error" role="alert">{errors.submit}</p>}{submitting&&<div className="upload-progress"><span style={{width:`${progress}%`}}/><b>{progress?`Uploading payment proof · ${progress}%`:"Submitting securely…"}</b></div>}</>}
 <footer className="form-actions">{step>1?<button className="outline-button" onClick={()=>setStep(s=>s-1)} disabled={submitting}><ChevronLeft/>Previous</button>:<Link className="outline-button" href="/">Cancel</Link>} {step<4?<button className="gold-button" onClick={next}>Continue<ChevronRight/></button>:<button className="gold-button" onClick={submit} disabled={submitting}>{submitting?"Submitting…":"Submit Registration"}</button>}</footer></section></main>{showTerms&&<div className="terms-modal-root"><button type="button" className="terms-modal-backdrop" aria-label="Close Registration Terms" onClick={()=>setShowTerms(false)}/><section className="terms-modal" role="dialog" aria-modal="true" aria-labelledby="registration-terms-title"><header><div><span>REGISTRATION TERMS</span><h2 id="registration-terms-title">Please review before registering</h2></div><button type="button" aria-label="Close Registration Terms" onClick={()=>setShowTerms(false)}><X/></button></header><div className="terms-modal-content"><h3>Registration status</h3><p>A submitted registration is not confirmed until the organiser verifies the proof of payment and approves the registration.</p><h3>Accuracy</h3><p>You are responsible for ensuring that all submitted information is complete and accurate.</p><h3>Payment verification</h3><p>The organiser may request a clearer or corrected proof of payment. A rejected payment does not create a confirmed registration.</p><h3>Programme information</h3><p>Event dates, venue, speakers and detailed schedules may be updated by the organiser when necessary.</p></div><footer><button type="button" className="outline-button" onClick={()=>setShowTerms(false)}>Not Yet</button><button type="button" className="gold-button" onClick={()=>{update("termsAccepted",true);setErrors(current=>{const next={...current};delete next.termsAccepted;return next});setShowTerms(false)}}><Check/>I Agree &amp; Continue</button></footer></section></div>}</PublicLayout>}
function FormHead({number,title}:{number:string;title:string}){return <div className="form-head"><span>{number}</span><h2>{title}</h2></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="public-field"><span>{label} *</span>{children}{error&&<small className="form-error" role="alert">{error}</small>}</label>}
function SelectField({label,value,values,onChange,error}:{label:string;value:string;values:string[];onChange:(v:string)=>void;error?:string}){return <Field label={label} error={error}><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Select an option</option>{values.map(x=><option key={x}>{x}</option>)}</select></Field>}
function CheckField({checked,onChange,error,children}:{checked:boolean;onChange:(v:boolean)=>void;error?:string;children:React.ReactNode}){return <label className="check-field"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{children}{error&&<small className="form-error" role="alert">{error}</small>}</span></label>}
